### ISSUE TITLE
tcn-client Tests Hanging on Github Actions

### ISSUE THREAD

**Issue by haydenridd** [covid19risk/covidwatch-android#136]
Once we added the tcn-client it broke CI because for some reason testing on that sub-module specifically hangs on Github actions. However I can do a full build where it runs all tests in Android Studio without any hanging.

**Comment by prabhuinbarajan** [comment]
@haydenridd  - added PR https://github.com/covid19risk/covidwatch-android/pull/137 , i suspect that the failures could be likely because of the nuances between sonarqube, multimodule gradle projects, and the path specifications. 

can you review the PR and test this once?  given how the git workflow is described, this problem kicks in only when you merge the PR to the develop branch.

**Comment by nkumarcc** [comment]
@prabhuinbarajan I'm not sure this fixed it. A PR was submitted yesterday (#138) and still had this issue.
