### ISSUE TITLE
Add pull refresh for events

### ISSUE THREAD

**Issue by BurningAXE** [covid19risk/covidwatch-android#71]
At least for the purposes of the MVP presentation to officials we need to ensure the following scenario works reliably:
- Two phones running Covid Watch are placed near each other for 15 minutes (make it less for the presentation!?)
 - On one of the phones the user marks him/herself as positive
- Notification is received on the other one

Check how much time it takes to download positive contacts from Firebase and whether it can be done real-time (through an observer or otherwise).

**Comment by Apisov** [comment]
Sounds about right but what about just a simple "Pull to Refresh" pattern to get the latest data? That would a be nice feature to have in the app in general instead of adding the code that we will remove later(that's how i understand this feature now). 

We don't need realtime listening of Firebase so that will be redundant code in the end.

**Comment by Apisov** [comment]
We decided(#90)  to use pull-to-refresh.

**Comment by nkumarcc** [comment]
Every 15 minutes when demoing instead of an hour, pull-to-refresh
